model_list:
  - model_name: claude-sonnet
    litellm_params:
      model: vertex_ai/claude-3-sonnet@20240229
      vertex_ai_project: "os.environ/GCP_PROJECT"
      vertex_ai_location: "os.environ/GCP_LOCATION"
  
  - model_name: claude-opus
    litellm_params:
      model: vertex_ai/claude-3-opus@20240229
      vertex_ai_project: "os.environ/GCP_PROJECT"
      vertex_ai_location: "os.environ/GCP_LOCATION"

  - model_name: gemini-pro
    litellm_params:
      model: vertex_ai/gemini-2.0-flash
      vertex_ai_project: "os.environ/GCP_PROJECT"
      vertex_ai_location: "os.environ/GCP_LOCATION"

  # Bedrock
  - model_name: claude-3
    litellm_params:
      model: bedrock/anthropic.claude-3-sonnet-20240229-v1:0
      aws_region_name: us-east-1
  
  # Ollama Model
  - model_name: llama-local
    litellm_params:
      model: ollama/llama3.2:1b
      api_base: http://127.0.0.1:11434

general_settings:
  master_key: ${PROXY_MASTER_KEY}
  use_auth: true
  request_timeout: 600
  store_model_in_db: false
  database_url: null
  audit_logs: false